# Basic set up for three package managers

version: 2
updates:
    target-branch: dev
    # Maintain dependencies for GitHub Actions
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
    # Maintain dependencies for rust
    -   package-ecosystem: "cargo"
        directory: "./inject-lib"
        schedule:
            interval: "daily"
    - package-ecosystem: "cargo"
      directory: "./dll-inject"
      schedule:
          interval: "daily"
          
