name: Build dll

on:
  push:
    branches: [staging,trying,dev,main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: "build-ci-dll"
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  build:
    name: "build"
    runs-on: windows-latest
    strategy:
      matrix:
        profile: [release,dev]
        target: [i686-pc-windows-msvc, i686-pc-windows-gnu ,x86_64-pc-windows-msvc, x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cbindgen
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.args }} --target ${{ matrix.target }} --profile ${{matrix.profile}} --package dll-inject
      - name: generate bindings
        working-directory: ./dll-inject
        run: cbindgen --config cbindgen.toml --crate dll-inject --output dll-inject.h

      - name: list dependencies
        working-directory: ./dll-inject/src
        run: rustc empty.rs --crate-type staticlib --print native-static-libs

      - uses: actions/upload-artifact@v3
        if: ${{matrix.profile}} == release
        with:
          name: dll-inject-${{ matrix.target}}-${{matrix.profile}}
          path: |
            dll-inject/dll-inject.h
            target/${{ matrix.target }}/${{matrix.profile}}/dll_inject.*

      - uses: actions/upload-artifact@v3
        if: ${{matrix.profile}} == dev
        with:
          name: dll-inject-${{ matrix.target}}-${{matrix.profile}}
          path: |
            dll-inject/dll-inject.h
            target/${{ matrix.target }}/debug/dll_inject.*
