---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
    push:
        branches: [staging,trying,dev,main]
        # Remove the line above to run when pushing to master
    pull_request:
        branches: [ main ]
env:
  CARGO_TERM_COLOR: always

###############
# Set the Job #
###############
jobs:
    ci:
        name: "fmt-ci"
        needs: [ "format"]
        runs-on: ubuntu-latest
        steps:
            - name: Done
              run: exit 0
    format:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --check --verbose --manifest-path ./inject-lib/Cargo.toml --package inject-lib -- --config-path ./inject-lib/rustfmt.toml
