name: Rust Tests

on:
  push:
    branches: [staging,trying,dev,main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: "build-ci"
    needs: ["build", "build-ubuntu"]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  build:
    name: "build"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        args: [-v] #--release -v,
        toolchain: ["beta","stable"]
        features: ['"alloc"','"alloc std"','"alloc x86tox64"','"alloc x86tox64 std"']
        target: [i686-pc-windows-msvc,x86_64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.args }} --no-default-features --features ${{ matrix.features }} --target ${{ matrix.target }} --package inject-lib
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.args }} --no-default-features --features ${{ matrix.features }} --target ${{ matrix.target }} --package inject-lib

  build-ubuntu:
    name: "build-ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args: [-v] #--release -v,
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.args }} --no-default-features --features "ntdll alloc" --package inject-lib
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.args }} --no-default-features --features "ntdll alloc" --package inject-lib
